pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: mvn-build
        identifier: mvnbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          sharedPaths:
            - /workspace
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: Copy Source to Shared Workspace
                  identifier: copy_source
                  spec:
                    shell: Sh
                    image: alpine
                    command: |
                      mkdir -p /workspace/src
                      cp -r . /workspace/src
                      echo "Source copied to /workspace/src"
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.9.6
                    shell: Sh
                    command: mvn clean package
              - step:
                  type: Semgrep
                  name: Semgrep_1
                  identifier: Semgrep_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: /workspace
                      detection: auto
                    advanced:
                      log:
                        level: info
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Build_image
        identifier: Build_image
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub
                    repo: sankaranarayananmurali/maven-v1
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Build Approval
        identifier: Build_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Docker image Approval
                  identifier: Docker_image_Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
              - step:
                  type: Email
                  name: Email_1
                  identifier: Email_1
                  spec:
                    to: sankaranarayanan.m@xenovex.com
                    cc: ""
                    subject: Build Approved
                    body: |-
                      Hi,
                      Build is approved!
                  timeout: 10m
        tags: {}
