pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: mvn-build
        identifier: mvnbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    connectorRef: dockerhub
                    image: sankaranarayananmurali/maven-v1:latest
                    shell: Sh
                    command: mvn clean test
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Build_image
        identifier: Build_image
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub
                    repo: sankaranarayananmurali/maven-v1
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Build Approval
        identifier: Build_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Docker image Approval
                  identifier: Docker_image_Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
