pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
        sparseCheckout: []
  notificationRules:
    - name: Pipeline Success Notification
      enabled: true
      pipelineEvents:
        - type: PipelineSuccess
      notificationMethod:
        type: Email
        spec:
          recipients:
            - <+pipeline.variables.EMAIL_TO>
    - name: Pipeline Failure Notification
      enabled: true
      pipelineEvents:
        - type: PipelineFailed
      notificationMethod:
        type: Email
        spec:
          recipients:
            - <+pipeline.variables.EMAIL_TO>
  variables:
    - name: nexus_url
      type: String
      value: http://10.10.10.20:8081/
    - name: nexus_username
      type: String
      value: admin
    - name: maven_group_id
      type: String
      value: com.example
    - name: maven_artifact_id
      type: String
      value: maven-app
    - name: maven_version
      type: String
      value: 1.0.0-${timestamp}-${buildNumber}
    - name: TOKEN
      type: String
      value: ""
    - name: DASHBOARD_ID
      type: String
      value: ""
    - name: SMTP_SERVER
      type: String
      value: ""
    - name: SMTP_PORT
      type: String
      value: ""
    - name: EMAIL_FROM
      type: String
      value: ""
    - name: EMAIL_TO
      type: String
      value: ""
  stages:
    - stage:
        name: Git-Clone
        identifier: GitClone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: mavengithubconnector
                    build:
                      type: branch
                      spec:
                        branch: master
        delegateSelectors:
          - docker-delegate
    - stage:
        name: mvn-build
        identifier: mvnbuild
        description: Maven build and Semgrep scan
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: maven_build
                  identifier: maven_build
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.9.6
                    shell: Sh
                    command: |
                      # Create .m2 directory if it doesn't exist
                      mkdir -p ~/.m2

                      # Generate settings.xml file with nexus-releases and nexus-snapshots server configurations
                      cat > ~/.m2/settings.xml << EOF
                      <?xml version="1.0" encoding="UTF-8"?>
                      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                http://maven.apache.org/xsd/settings-1.0.0.xsd">
                        <servers>
                          <server>
                            <id>nexus-releases</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                          <server>
                            <id>nexus-snapshots</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                        </servers>
                      </settings>
                      EOF

                      # Generate dynamic version with timestamp and build number
                      TIMESTAMP=$(date +%Y%m%d%H%M%S)
                      BUILD_NUMBER=<+pipeline.sequenceId>
                      DYNAMIC_VERSION="1.0.0-${TIMESTAMP}-${BUILD_NUMBER}"
                      echo "Generated dynamic version: ${DYNAMIC_VERSION}"

                      # Update version in pom.xml
                      mvn versions:set -DnewVersion=${DYNAMIC_VERSION} -DgenerateBackupPoms=false

                      # Run maven clean deploy which will automatically upload to Nexus
                      mvn clean deploy

                      # Export the dynamic version as an output variable
                      export MAVEN_VERSION=${DYNAMIC_VERSION}

                      # Export the artifact path as an output variable
                      ARTIFACT_PATH=$(find ./target -name "*.jar" -o -name "*.war" | head -1)
                      echo "Found artifact at: ${ARTIFACT_PATH}"
                      export ARTIFACT_PATH=${ARTIFACT_PATH}
                    envVariables:
                      NEXUS_USERNAME: <+pipeline.variables.nexus_username>
                      NEXUS_PASSWORD: <+secrets.getValue("nexus_password")>
                    outputVariables:
                      - name: MAVEN_VERSION
                      - name: ARTIFACT_PATH
                  timeout: 10m
            rollbackSteps: []
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Scan
        identifier: Scan
        description: ""
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_scan
                  identifier: Semgrep_scan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: .
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: critical
                    settings:
                      report:
                        enabled: true
                        format: json
                        path: semgrep-report.json
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
                  timeout: 10m
              - step:
                  type: Run
                  name: Email Scan Results
                  identifier: email_scan_results
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |
                      # Install required packages
                      apk add --no-cache curl jq

                      # Read the semgrep report file
                      echo "Reading semgrep scan results..."
                      if [ ! -f semgrep-report.json ]; then
                        echo "Error: semgrep-report.json file not found"
                        exit 1
                      fi

                      # Parse the report and format for email
                      TOTAL_FINDINGS=$(jq '.results | length' semgrep-report.json)
                      CRITICAL=$(jq '.results[] | select(.extra.severity == "ERROR") | .extra.severity' semgrep-report.json | wc -l)
                      HIGH=$(jq '.results[] | select(.extra.severity == "WARNING") | .extra.severity' semgrep-report.json | wc -l)
                      MEDIUM=$(jq '.results[] | select(.extra.severity == "INFO") | .extra.severity' semgrep-report.json | wc -l)
                      LOW=$(jq '.results[] | select(.extra.severity == "NONE") | .extra.severity' semgrep-report.json | wc -l)

                      # Generate timestamp
                      TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

                      # Create email content
                      EMAIL_SUBJECT="Semgrep Scan Results - Pipeline: <+pipeline.name>"
                      EMAIL_BODY="""
                      <html>
                      <body>
                      <h2>Semgrep Security Scan Results</h2>
                      <p><b>Pipeline:</b> <+pipeline.name> (<+pipeline.identifier>)</p>
                      <p><b>Execution ID:</b> <+pipeline.executionId></p>
                      <p><b>Triggered by:</b> <+pipeline.triggeredBy.name></p>
                      <p><b>Scan completed at:</b> $TIMESTAMP</p>

                      <h3>Scan Summary:</h3>
                      <ul>
                        <li>Total findings: $TOTAL_FINDINGS</li>
                        <li>Critical: $CRITICAL</li>
                        <li>High: $HIGH</li>
                        <li>Medium: $MEDIUM</li>
                        <li>Low: $LOW</li>
                      </ul>

                      <p><a href="<+pipeline.executionUrl>">View full pipeline execution</a></p>
                      </body>
                      </html>
                      """

                      # Save email content to file
                      echo "$EMAIL_BODY" > email_content.html

                      # Send email using curl and SMTP
                      echo "Sending email with scan results..."
                      curl --url "smtp://$SMTP_SERVER:$SMTP_PORT" \
                        --ssl-reqd \
                        --mail-from "$EMAIL_FROM" \
                        --mail-rcpt "$EMAIL_TO" \
                        --user "$EMAIL_FROM:$EMAIL_PASSWORD" \
                        -H "Subject: $EMAIL_SUBJECT" \
                        -H "Content-Type: text/html" \
                        --upload-file email_content.html

                      echo "Email sent successfully!"
                    envVariables:
                      SMTP_SERVER: <+pipeline.variables.SMTP_SERVER>
                      SMTP_PORT: <+pipeline.variables.SMTP_PORT>
                      EMAIL_FROM: <+pipeline.variables.EMAIL_FROM>
                      EMAIL_TO: <+pipeline.variables.EMAIL_TO>
                      EMAIL_PASSWORD: <+secrets.getValue("email_password")>
                  timeout: 10m
            rollbackSteps: []
    - stage:
        name: Build_image
        identifier: Build_image
        description: Docker image build and push
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub
                    repo: sankaranarayananmurali/maven-v1
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
                    caching: true
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1
                      requests:
                        memory: 1Gi
                        cpu: 0.5
                  timeout: 10m
            rollbackSteps: []
    - stage:
        name: Build Approval
        identifier: Build_Approval
        description: Approval stage for Docker image
        type: Approval
        delegateSelectors:
          - docker-delegate
        spec:
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Docker Image Approval
                  identifier: Docker_image_Approval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
              - step:
                  identifier: Http_1
                  name: Dashboard Report
                  type: Http
                  timeout: 10m
                  spec:
                    method: GET
                    url: <+pipeline.variables.nexus_url>/service/rest/v1/components?repository=maven-releases&group=<+pipeline.variables.maven_group_id>&name=<+pipeline.variables.maven_artifact_id>
                    headers:
                      - key: Authorization
                        value: Basic <+pipeline.variables.nexus_username>:<+secrets.getValue("Nexus Password")>
                      - key: Accept
                        value: application/json
                    assertion: <+httpResponseCode> == 200
                    outputVariables:
                      - name: dashboard_data
                        type: String
                        value: <+httpResponseBody>
            rollbackSteps: []
        tags: {}
  description: This pipeline was updated by Harness AI on 2025-12-11 10:58:16 UTC by sankaranarayanan.m.
