pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
        sparseCheckout: []
  variables:
    - name: nexus_url
      type: String
      value: http://10.10.10.20:8081/
    - name: nexus_username
      type: String
      value: admin
    - name: maven_group_id
      type: String
      value: com.example
    - name: maven_artifact_id
      type: String
      value: maven-app
    - name: maven_version
      type: String
      value: 1.0.0-${timestamp}-${buildNumber}
  stages:
    - stage:
        name: mvn-build
        identifier: mvnbuild
        description: Maven build and Semgrep scan
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: maven_build
                  identifier: maven_build
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.9.6
                    shell: Sh
                    command: |
                      # Check if pom.xml exists
                      if [ ! -f "pom.xml" ]; then
                        echo "ERROR: pom.xml not found in the current directory!"
                        exit 1
                      fi

                      # Create .m2 directory if it doesn't exist
                      mkdir -p ~/.m2

                      # Generate settings.xml file with nexus-releases and nexus-snapshots server configurations
                      cat > ~/.m2/settings.xml << EOF
                      <?xml version="1.0" encoding="UTF-8"?>
                      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                http://maven.apache.org/xsd/settings-1.0.0.xsd">
                        <servers>
                          <server>
                            <id>nexus-releases</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                          <server>
                            <id>nexus-snapshots</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                        </servers>
                      </settings>
                      EOF

                      # Generate dynamic version with timestamp and build number
                      TIMESTAMP=$(date +%Y%m%d%H%M%S)
                      BUILD_NUMBER=<+pipeline.sequenceId>
                      DYNAMIC_VERSION="1.0.0-${TIMESTAMP}-${BUILD_NUMBER}"
                      echo "Generated dynamic version: ${DYNAMIC_VERSION}"

                      # Update version in pom.xml with validation
                      mvn versions:set -DnewVersion=${DYNAMIC_VERSION} -DgenerateBackupPoms=false
                      if [ $? -ne 0 ]; then
                        echo "ERROR: Failed to update version in pom.xml!"
                        exit 1
                      fi
                      echo "Successfully updated version in pom.xml to ${DYNAMIC_VERSION}"

                      # Run maven clean deploy which will automatically upload to Nexus
                      mvn clean deploy
                      if [ $? -ne 0 ]; then
                        echo "ERROR: Maven build or deploy failed!"
                        exit 1
                      fi
                      echo "Maven build and deploy completed successfully"

                      # Export the dynamic version as an output variable
                      export MAVEN_VERSION=${DYNAMIC_VERSION}

                      # Export the artifact path as an output variable with validation
                      ARTIFACT_PATH=$(find ./target -name "*.jar" -o -name "*.war" | head -1)
                      if [ -z "$ARTIFACT_PATH" ]; then
                        echo "ERROR: No artifact (JAR/WAR) found in target directory!"
                        exit 1
                      fi
                      echo "Found artifact at: ${ARTIFACT_PATH}"

                      # Validate artifact exists and has content
                      if [ ! -f "$ARTIFACT_PATH" ]; then
                        echo "ERROR: Artifact file does not exist at path: ${ARTIFACT_PATH}"
                        exit 1
                      fi

                      if [ ! -s "$ARTIFACT_PATH" ]; then
                        echo "ERROR: Artifact file is empty: ${ARTIFACT_PATH}"
                        exit 1
                      fi

                      echo "Artifact validation successful"
                      export ARTIFACT_PATH=${ARTIFACT_PATH}
                    envVariables:
                      NEXUS_USERNAME: <+pipeline.variables.nexus_username>
                      NEXUS_PASSWORD: <+secrets.getValue("nexus_password")>
                    outputVariables:
                      - name: MAVEN_VERSION
                      - name: ARTIFACT_PATH
                  timeout: 10m
            rollbackSteps: []
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Scan
        identifier: Scan
        description: ""
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          sharedPaths:
            - /shared
          execution:
            steps:
              - step:
                  name: Semgrep_and_Upload
                  identifier: Semgrep_and_Upload
                  type: Run
                  spec:
                    connectorRef: account.harnessImage
                    image: returntocorp/semgrep:latest
                    shell: Bash
                    command: |
                      echo "=== Running Semgrep scan ==="

                      # Check if jq is installed and install if needed
                      if ! command -v jq &> /dev/null; then
                        echo "jq not found. Installing jq..."
                        apt-get update && apt-get install -y jq || (
                          apk add --no-cache jq || (
                            echo "Failed to install jq. Exiting."
                            exit 1
                          )
                        )
                      fi
                      echo "jq is available: $(which jq)"

                      # Run Semgrep scan and output to JSON format
                      semgrep scan \
                        --config=auto \
                        --json \
                        --output=semgrep-report.json \
                        .

                      # Store scan exit code
                      SCAN_EXIT_CODE=$?

                      # Check if report was generated
                      if [ ! -f "semgrep-report.json" ]; then
                        echo "ERROR: semgrep-report.json file NOT generated!"
                        exit 1
                      fi

                      # Validate file size
                      FILE_SIZE=$(stat -c%s "semgrep-report.json" 2>/dev/null || stat -f%z "semgrep-report.json")
                      if [ "$FILE_SIZE" -eq 0 ]; then
                        echo "ERROR: semgrep-report.json is empty!"
                        exit 1
                      fi

                      echo "Report generated:"
                      ls -lh semgrep-report.json

                      # Extract findings counts for output variables
                      TOTAL_FINDINGS=$(jq '.results | length' semgrep-report.json)
                      if [ $? -ne 0 ]; then
                        echo "ERROR: Failed to parse JSON with jq. Check report format."
                        exit 1
                      fi

                      CRITICAL_FINDINGS=$(jq '.results | map(select(.extra.severity == "ERROR")) | length' semgrep-report.json)
                      HIGH_FINDINGS=$(jq '.results | map(select(.extra.severity == "WARNING")) | length' semgrep-report.json)
                      MEDIUM_FINDINGS=$(jq '.results | map(select(.extra.severity == "INFO")) | length' semgrep-report.json)
                      LOW_FINDINGS=$(jq '.results | map(select(.extra.severity == "NONE")) | length' semgrep-report.json)

                      echo "Findings summary:"
                      echo "Total: $TOTAL_FINDINGS"
                      echo "Critical: $CRITICAL_FINDINGS"
                      echo "High: $HIGH_FINDINGS"
                      echo "Medium: $MEDIUM_FINDINGS"
                      echo "Low: $LOW_FINDINGS"

                      # Export findings as output variables
                      export TOTAL_FINDINGS="$TOTAL_FINDINGS"
                      export CRITICAL_FINDINGS="$CRITICAL_FINDINGS"
                      export HIGH_FINDINGS="$HIGH_FINDINGS"
                      export MEDIUM_FINDINGS="$MEDIUM_FINDINGS"
                      export LOW_FINDINGS="$LOW_FINDINGS"

                      echo "=== Uploading to Nexus ==="

                      # Validate Nexus URL
                      if [[ ! "$NEXUS_URL" =~ ^https?:// ]]; then
                        echo "WARNING: Nexus URL does not start with http:// or https://"
                      fi

                      # Upload report to Nexus
                      HTTP_RESPONSE=$(curl -s -w "%{http_code}" -o /tmp/curl_response \
                        -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" \
                        --upload-file semgrep-report.json \
                        "${NEXUS_URL}/repository/raw-reports/scan-reports/${MAVEN_GROUP_ID}/${MAVEN_ARTIFACT_ID}/semgrep-report.json")

                      # Check upload status
                      if [ "$HTTP_RESPONSE" -lt 200 ] || [ "$HTTP_RESPONSE" -ge 300 ]; then
                        echo "Upload FAILED. HTTP $HTTP_RESPONSE"
                        cat /tmp/curl_response
                        export UPLOAD_STATUS="failed"
                        exit 1
                      else
                        echo "Upload successful!"
                        export UPLOAD_STATUS="success"
                      fi

                      # Return original scan exit code
                      exit $SCAN_EXIT_CODE
                    envVariables:
                      NEXUS_USERNAME: <+pipeline.variables.nexus_username>
                      NEXUS_PASSWORD: <+secrets.getValue("nexus_password")>
                      NEXUS_URL: <+pipeline.variables.nexus_url>
                      MAVEN_GROUP_ID: <+pipeline.variables.maven_group_id>
                      MAVEN_ARTIFACT_ID: <+pipeline.variables.maven_artifact_id>
                    outputVariables:
                      - name: TOTAL_FINDINGS
                      - name: CRITICAL_FINDINGS
                      - name: HIGH_FINDINGS
                      - name: MEDIUM_FINDINGS
                      - name: LOW_FINDINGS
                      - name: UPLOAD_STATUS
                    resources:
                      limits:
                        memory: 1Gi
                        cpu: 500m
                      requests:
                        memory: 512Mi
                        cpu: 250m
                  timeout: 10m
            rollbackSteps: []
    - stage:
        name: SCA_Scan
        identifier: SCA_Scan
        description: ""
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Owasp
                  name: Owasp_1
                  identifier: Owasp_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
            rollbackSteps: []
    - stage:
        name: Build_image
        identifier: Build_image
        description: Docker image build and push
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub
                    repo: sankaranarayananmurali/maven-v1
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
                    caching: true
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1
                      requests:
                        memory: 1Gi
                        cpu: 0.5
                  timeout: 10m
            rollbackSteps: []
    - stage:
        name: Build Approval
        identifier: Build_Approval
        description: Approval stage for Docker image
        type: Approval
        delegateSelectors:
          - docker-delegate
        spec:
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Docker Image Approval
                  identifier: Docker_image_Approval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information and approve the pipeline progression

                      SCAN RESULTS SUMMARY:
                      - Security scan completed with Semgrep
                      - Scan reports uploaded to Nexus repository
                      - OWASP dependency check completed

                      ARTIFACT DETAILS:
                      - Docker image: sankaranarayananmurali/maven-v1:<+pipeline.sequenceId>
                      - Maven artifact: <+pipeline.variables.maven_group_id>:<+pipeline.variables.maven_artifact_id>:<+pipeline.variables.maven_version>

                      Please verify these artifacts before approving deployment.
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
              - step:
                  type: Email
                  name: Email_Notification
                  identifier: Email_1
                  spec:
                    to: sankaranarayanan.m@xenovex.com
                    cc: ""
                    subject: Build Approved
                    body: |-
                      Hi,

                      Build has been approved successfully!

                      Build Details:
                      - Pipeline: <+pipeline.name>
                      - Build Number: <+pipeline.sequenceId>
                      - Triggered By: <+pipeline.triggeredBy.name>
                      - Execution URL: <+pipeline.executionUrl>

                      Scan Results:
                      - Semgrep Findings: <+pipeline.stages.Scan.spec.execution.steps.Semgrep_and_Upload.output.outputVariables.TOTAL_FINDINGS>
                      - OWASP SCA Scan Completed: <+pipeline.stages.SCA_Scan.status>

                      Artifact Information:
                      - Maven Version: <+pipeline.stages.mvnbuild.spec.execution.steps.maven_build.output.outputVariables.MAVEN_VERSION>
                      - Docker Image: sankaranarayananmurali/maven-v1:<+pipeline.sequenceId>

                      This is an automated notification from Harness CI/CD.
                  timeout: 10m
            rollbackSteps: []
  description: This pipeline was updated by Harness AI on 2025-12-10 08:46:44 UTC by sankaranarayanan.m.
