pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
        sparseCheckout: []
  variables:
    - name: nexus_url
      type: String
      value: http://10.10.10.20:8081/
    - name: nexus_username
      type: String
      value: admin
    - name: maven_group_id
      type: String
      value: com.example
    - name: maven_artifact_id
      type: String
      value: maven-app
    - name: maven_version
      type: String
      value: 1.0.0-${timestamp}-${buildNumber}
  stages:
    - stage:
        name: mvn-build
        identifier: mvnbuild
        description: Maven build and Semgrep scan
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: maven_build
                  identifier: maven_build
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.9.6
                    shell: Sh
                    command: |
                      mkdir -p ~/.m2

                      cat > ~/.m2/settings.xml << EOF
                      <?xml version="1.0" encoding="UTF-8"?>
                      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                http://maven.apache.org/xsd/settings-1.0.0.xsd">
                        <servers>
                          <server>
                            <id>nexus-releases</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                          <server>
                            <id>nexus-snapshots</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                        </servers>
                      </settings>
                      EOF

                      TIMESTAMP=$(date +%Y%m%d%H%M%S)
                      BUILD_NUMBER=<+pipeline.sequenceId>
