pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
  stages:
    - stage:
        name: mvn-build
        identifier: mvnbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerhub
                    image: sankaranarayananmurali/maven-v1:latest
                    shell: Sh
                    command: mvn clean test
        delegateSelectors:
          - docker-delegate
    - stage:
        name: docker_build
        identifier: docker_build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub
                    repo: sankaranarayananmurali/maven-v1
                    tags:
                      - <+pipeline.sequenceId>
