pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
        sparseCheckout: []
  variables:
    - name: nexus_url
      type: String
      value: http://10.10.10.20:8081/
    - name: nexus_username
      type: String
      value: admin
    - name: maven_group_id
      type: String
      value: com.example
    - name: maven_artifact_id
      type: String
      value: maven-app
    - name: maven_version
      type: String
      value: 1.0.0-${timestamp}-${buildNumber}
  stages:
    - stage:
        name: mvn-build
        identifier: mvnbuild
        description: Maven build and Semgrep scan
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: maven_build
                  identifier: maven_build
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.9.6
                    shell: Sh
                    command: |
                      # Create .m2 directory if it doesn't exist
                      mkdir -p ~/.m2

                      # Generate settings.xml file with nexus-releases and nexus-snapshots server configurations
                      cat > ~/.m2/settings.xml << EOF
                      <?xml version="1.0" encoding="UTF-8"?>
                      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                http://maven.apache.org/xsd/settings-1.0.0.xsd">
                        <servers>
                          <server>
                            <id>nexus-releases</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                          <server>
                            <id>nexus-snapshots</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                        </servers>
                      </settings>
                      EOF

                      # Generate dynamic version with timestamp and build number
                      TIMESTAMP=$(date +%Y%m%d%H%M%S)
                      BUILD_NUMBER=<+pipeline.sequenceId>
                      DYNAMIC_VERSION="1.0.0-${TIMESTAMP}-${BUILD_NUMBER}"
                      echo "Generated dynamic version: ${DYNAMIC_VERSION}"

                      # Update version in pom.xml
                      mvn versions:set -DnewVersion=${DYNAMIC_VERSION} -DgenerateBackupPoms=false

                      # Run maven clean deploy which will automatically upload to Nexus
                      mvn clean deploy

                      # Export the dynamic version as an output variable
                      export MAVEN_VERSION=${DYNAMIC_VERSION}

                      # Export the artifact path as an output variable
                      ARTIFACT_PATH=$(find ./target -name "*.jar" -o -name "*.war" | head -1)
                      echo "Found artifact at: ${ARTIFACT_PATH}"
                      export ARTIFACT_PATH=${ARTIFACT_PATH}
                    envVariables:
                      NEXUS_USERNAME: <+pipeline.variables.nexus_username>
                      NEXUS_PASSWORD: <+secrets.getValue("nexus_password")>
                    outputVariables:
                      - name: MAVEN_VERSION
                      - name: ARTIFACT_PATH
                  timeout: 10m
            rollbackSteps: []
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Scan
        identifier: Scan
        description: ""
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_scan
                  identifier: Semgrep_scan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: .
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: critical
                    outputVariables:
                      - name: semgrep_findings
                      - name: total_findings
                      - name: critical_findings
                      - name: high_findings
                      - name: medium_findings
                      - name: low_findings
                    settings:
                      report:
                        enabled: true
                        format: json
                        path: semgrep-report.json
                        directory: /shared/reports
                        verbose: true
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
                  timeout: 10m
              - step:
                  identifier: upload_scan_report
                  name: Upload Scan Report to Nexus
                  type: Run
                  timeout: 10m
                  spec:
                    connectorRef: account.harnessImage
                    image: curlimages/curl:latest
                    shell: Sh
                    command: |
                      echo "Uploading semgrep-report.json to Nexus Raw repository..."

                      # Debug: List current directory contents
                      echo "Current directory contents:"
                      ls -la

                      # Debug: Check shared paths
                      echo "Checking shared paths:"
                      ls -la /harness/

                      # Look for the report in the shared location
                      REPORT_PATH="./semgrep-report.json"
                      if [ ! -f "$REPORT_PATH" ]; then
                        echo "Report not found in current directory, checking shared paths..."
                        REPORT_PATH="/harness/semgrep-report.json"
                        if [ ! -f "$REPORT_PATH" ]; then
                          echo "Error: semgrep-report.json file not found in any location!"
                          exit 1
                        fi
                      fi

                      echo "Found report at: $REPORT_PATH"

                      # Validate JSON format
                      if ! jq empty "$REPORT_PATH" 2>/dev/null; then
                        echo "Error: $REPORT_PATH is not a valid JSON file!"
                        exit 1
                      fi

                      # Upload to Nexus
                      echo "Uploading report to Nexus from $REPORT_PATH"
                      HTTP_RESPONSE=$(curl -s -w "%{http_code}" -o /tmp/curl_response \
                      -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" \
                      --upload-file "$REPORT_PATH" \
                      "http://10.10.10.20:8081/repository/raw-reports/scan-reports/com.example/maven-app/scan_report.json")

                      # Check HTTP response code
                      if [ "$HTTP_RESPONSE" -lt 200 ] || [ "$HTTP_RESPONSE" -ge 300 ]; then
                        echo "Error: Failed to upload scan report to Nexus! HTTP Status: $HTTP_RESPONSE"
                        cat /tmp/curl_response
                        exit 1
                      fi

                      echo "Scan report uploaded successfully!"
                      export UPLOAD_STATUS="success"
                    envVariables:
                      NEXUS_USERNAME: <+pipeline.variables.nexus_username>
                      NEXUS_PASSWORD: <+secrets.getValue("nexus_password")>
                    outputVariables:
                      - name: UPLOAD_STATUS
            rollbackSteps: []
    - stage:
        name: SCA_Scan
        identifier: SCA_Scan
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Owasp
                  name: Owasp_1
                  identifier: Owasp_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
    - stage:
        name: Build_image
        identifier: Build_image
        description: Docker image build and push
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub
                    repo: sankaranarayananmurali/maven-v1
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
                    caching: true
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1
                      requests:
                        memory: 1Gi
                        cpu: 0.5
                  timeout: 10m
            rollbackSteps: []
    - stage:
        name: Build Approval
        identifier: Build_Approval
        description: Approval stage for Docker image
        type: Approval
        delegateSelectors:
          - docker-delegate
        spec:
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Docker Image Approval
                  identifier: Docker_image_Approval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information and approve the pipeline progression

                      SCAN RESULTS SUMMARY:
                      - Security scan completed with Semgrep
                      - Scan reports uploaded to Nexus repository
                      - OWASP dependency check completed

                      ARTIFACT DETAILS:
                      - Docker image: sankaranarayananmurali/maven-v1:<+pipeline.sequenceId>
                      - Maven artifact: <+pipeline.variables.maven_group_id>:<+pipeline.variables.maven_artifact_id>:<+pipeline.variables.maven_version>

                      Please verify these artifacts before approving deployment.
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
              - step:
                  type: Email
                  name: Email_Notification
                  identifier: Email_1
                  spec:
                    to: sankaranarayanan.m@xenovex.com
                    cc: ""
                    subject: Build Approved
                    body: |-
                      Hi,

                      Build has been approved successfully!

                      Build Details:
                      - Pipeline: <+pipeline.name>
                      - Build Number: <+pipeline.sequenceId>
                      - Triggered By: <+pipeline.triggeredBy.name>
                      - Execution URL: <+pipeline.executionUrl>

                      Scan Results:
                      - Semgrep Findings: <+pipeline.stages.Scan.spec.execution.steps.Semgrep_scan.output.outputVariables.semgrep_findings>
                      - OWASP SCA Scan Completed: <+pipeline.stages.SCA_Scan.status>

                      Artifact Information:
                      - Maven Version: <+pipeline.stages.mvnbuild.spec.execution.steps.maven_build.output.outputVariables.MAVEN_VERSION>
                      - Docker Image: sankaranarayananmurali/maven-v1:<+pipeline.sequenceId>

                      This is an automated notification from Harness CI/CD.
                  timeout: 10m
            rollbackSteps: []
  description: This pipeline was updated by Harness AI on 2025-12-10 08:02:57 UTC by sankaranarayanan.m.
