pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
        sparseCheckout: []
  variables:
    - name: nexus_url
      type: String
      value: http://10.10.10.20:8081/
    - name: nexus_username
      type: String
      value: admin
    - name: maven_group_id
      type: String
      value: com.example
    - name: maven_artifact_id
      type: String
      value: maven-app
    - name: maven_version
      type: String
      value: 1.0.0-${timestamp}-${buildNumber}
  stages:
    - stage:
        name: mvn-build
        identifier: mvnbuild
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: maven_build
                  identifier: maven_build
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.9.6
                    shell: Sh
                    command: |
                      mkdir -p ~/.m2

                      cat > ~/.m2/settings.xml << EOF
                      <?xml version="1.0" encoding="UTF-8"?>
                      <settings>
                        <servers>
                          <server>
                            <id>nexus-releases</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                          <server>
                            <id>nexus-snapshots</id>
                            <username>${NEXUS_USERNAME}</username>
                            <password>${NEXUS_PASSWORD}</password>
                          </server>
                        </servers>
                      </settings>
                      EOF

                      TIMESTAMP=$(date +%Y%m%d%H%M%S)
                      BUILD_NUMBER=<+pipeline.sequenceId>
                      DYNAMIC_VERSION="1.0.0-${TIMESTAMP}-${BUILD_NUMBER}"
                      echo "Generated dynamic version: ${DYNAMIC_VERSION}"

                      mvn versions:set -DnewVersion=${DYNAMIC_VERSION} -DgenerateBackupPoms=false
                      mvn clean deploy

                      export MAVEN_VERSION=${DYNAMIC_VERSION}
                      ARTIFACT_PATH=$(find ./target -name "*.jar" | head -1)
                      echo "Found artifact: ${ARTIFACT_PATH}"
                      export ARTIFACT_PATH=${ARTIFACT_PATH}
                    envVariables:
                      NEXUS_USERNAME: <+pipeline.variables.nexus_username>
                      NEXUS_PASSWORD: <+secrets.getValue("nexus_password")>
                    outputVariables:
                      - name: MAVEN_VERSION
                      - name: ARTIFACT_PATH
                  timeout: 10m
          rollbackSteps: []
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Security Scan
        identifier: security_scan
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep Scan
                  identifier: semgrep_scan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: .
                      detection: manual
                      name: maven-barista
                      variant: master
                    advanced:
                      log:
                        level: info
                    settings:
                      report:
                        enabled: true
                        format: sarif
                        path: /security-reports/semgrep-report.sarif
                        directory: /security-reports
                    outputVariables:
                      - name: report_path
                  timeout: 10m
              - step:
                  type: Run
                  name: Process and Upload SARIF Report
                  identifier: process_upload_sarif
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: |
                      # Update certificates and install required tools
                      apk add --no-cache ca-certificates
                      apk update
                      apk add --no-cache curl jq findutils

                      # Define possible SARIF file locations to search
                      echo "Searching for SARIF files..."
                      SARIF_FILE=$(find / -name "*.sarif" -type f 2>/dev/null | head -1)

                      if [ -z "$SARIF_FILE" ]; then
                        echo "No SARIF file found, checking for JSON reports instead..."
                        SARIF_FILE=$(find / -name "semgrep-report.json" -type f 2>/dev/null | head -1)
                      fi

                      if [ -z "$SARIF_FILE" ]; then
                        echo "ERROR: No SARIF or Semgrep report files found"
                        exit 1
                      fi

                      echo "Found report file: $SARIF_FILE"

                      # Create directory for processed files
                      mkdir -p /tmp/security-reports

                      # Validate and process the file
                      if jq empty "$SARIF_FILE" 2>/dev/null; then
                        echo "File is valid JSON, processing..."
                        cp "$SARIF_FILE" /tmp/security-reports/semgrep-report.json
                      else
                        echo "File is not valid JSON, cannot process"
                        exit 1
                      fi

                      # Generate timestamp for unique filename
                      TS=$(date +%Y%m%d-%H%M%S)
                      TARGET_NAME="semgrep-report-$TS.json"

                      # Upload to Nexus
                      echo "Uploading report to Nexus as $TARGET_NAME"
                      HTTP_CODE=$(curl -s -w "%{http_code}" \
                        -u "$NEXUS_USER:$NEXUS_PASS" \
                        --upload-file /tmp/security-reports/semgrep-report.json \
                        "$NEXUS_URL/$TARGET_NAME")

                      if [[ $HTTP_CODE -ge 200 && $HTTP_CODE -lt 300 ]]; then
                        echo "SUCCESS: Uploaded report to $TARGET_NAME"
                        echo "HTTP Status: $HTTP_CODE"
                        export REPORT_PATH="/tmp/security-reports/semgrep-report.json"
                        export UPLOADED_REPORT_NAME="$TARGET_NAME"
                      else
                        echo "ERROR: Failed to upload report. HTTP Status: $HTTP_CODE"
                        exit 1
                      fi
                    envVariables:
                      NEXUS_USER: <+pipeline.variables.nexus_username>
                      NEXUS_PASS: <+secrets.getValue("nexus_password")>
                      NEXUS_URL: http://10.10.10.20:8081/repository/sto-reports
                    outputVariables:
                      - name: REPORT_PATH
                        type: String
                        value: REPORT_PATH
                      - name: UPLOADED_REPORT_NAME
                        type: String
                        value: UPLOADED_REPORT_NAME
                  timeout: 10m
              - step:
                  type: Run
                  name: Debug SARIF Files
                  identifier: debug_sarif
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |
                      echo "=== Searching for SARIF files ==="
                      find / -name "*.sarif" -type f 2>/dev/null || echo "No SARIF files found"

                      echo "=== Searching for JSON report files ==="
                      find / -name "semgrep-report.json" -type f 2>/dev/null || echo "No semgrep-report.json files found"

                      echo "=== Contents of /security-reports ==="
                      ls -la /security-reports/ 2>/dev/null || echo "/security-reports not found"

                      echo "=== Contents of /harness ==="
                      ls -la /harness/ 2>/dev/null || echo "/harness not found"

                      echo "=== Contents of current directory ==="
                      ls -la .

                      echo "=== File types in current directory ==="
                      find . -type f -exec file {} \; | grep -i "json\|sarif"
                    timeout: 10m
            rollbackSteps: []
          rollbackSteps: []
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Build_image
        identifier: Build_image
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub
                    repo: sankaranarayananmurali/maven-v1
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
                  timeout: 10m
          rollbackSteps: []
    - stage:
        name: Build Approval
        identifier: Build_Approval
        type: Approval
        delegateSelectors:
          - docker-delegate
        spec:
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Docker Image Approval
                  identifier: Docker_image_Approval
                  timeout: 1d
                  spec:
                    approvalMessage: Please review and approve this build.
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
              - step:
                  type: Email
                  name: Email_Notification
                  identifier: Email_1
                  spec:
                    to: sankaranarayanan.m@xenovex.com
                    subject: Build Approved
                    body: |
                      Hi,
                      Build is approved!
                  timeout: 10m
          rollbackSteps: []
  description: This pipeline was updated by Harness AI on 2025-12-10 14:02:23 UTC by sankaranarayanan.m.
