pipeline:
  name: simple-maven
  identifier: simplemaven
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: mavengithubconnector
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: mvn-build
        identifier: mvnbuild
        description: Maven build and Semgrep scan
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: Run
                  name: maven_build
                  identifier: maven_build
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.9.6
                    shell: Sh
                    command: mvn clean package
            rollbackSteps: []
        delegateSelectors:
          - docker-delegate
    - stage:
        name: Scan
        identifier: Scan
        description: ""
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_scan
                  identifier: Semgrep_scan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      workspace: .
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: critical
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
              - step:
                  type: Run
                  name: Parse Semgrep Results
                  identifier: parse_results
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |
                      # Parse Semgrep scan results
                      echo "Parsing Semgrep scan results..."

                      # Extract vulnerability counts by severity
                      CRITICAL_COUNT=$(grep -c '"severity":"critical"' semgrep-results.json || echo 0)
                      HIGH_COUNT=$(grep -c '"severity":"high"' semgrep-results.json || echo 0)
                      MEDIUM_COUNT=$(grep -c '"severity":"medium"' semgrep-results.json || echo 0)
                      LOW_COUNT=$(grep -c '"severity":"low"' semgrep-results.json || echo 0)

                      # Extract affected files
                      AFFECTED_FILES=$(grep -o '"path":"[^"]*"' semgrep-results.json | sort | uniq | wc -l)

                      # Set output variables
                      export CRITICAL_VULNS=$CRITICAL_COUNT
                      export HIGH_VULNS=$HIGH_COUNT
                      export MEDIUM_VULNS=$MEDIUM_COUNT
                      export LOW_VULNS=$LOW_COUNT
                      export TOTAL_VULNS=$((CRITICAL_COUNT + HIGH_COUNT + MEDIUM_COUNT + LOW_COUNT))
                      export AFFECTED_FILES_COUNT=$AFFECTED_FILES

                      # Print summary
                      echo "Vulnerability Summary:"
                      echo "Critical: $CRITICAL_VULNS"
                      echo "High: $HIGH_VULNS"
                      echo "Medium: $MEDIUM_VULNS"
                      echo "Low: $LOW_VULNS"
                      echo "Total: $TOTAL_VULNS"
                      echo "Affected Files: $AFFECTED_FILES_COUNT"
                    outputVariables:
                      - name: CRITICAL_VULNS
                      - name: HIGH_VULNS
                      - name: MEDIUM_VULNS
                      - name: LOW_VULNS
                      - name: TOTAL_VULNS
                      - name: AFFECTED_FILES_COUNT
                  timeout: 10m
              - step:
                  type: Run
                  name: Generate Scan Report
                  identifier: generate_report
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |
                      # Create a summary report of scan findings
                      echo "Generating security scan summary report..."

                      # Extract key statistics from scan results
                      TOTAL_FINDINGS=$(echo "$SCAN_RESULTS" | grep -c "finding")
                      CRITICAL_FINDINGS=$(echo "$SCAN_RESULTS" | grep -c "critical")
                      HIGH_FINDINGS=$(echo "$SCAN_RESULTS" | grep -c "high")
                      MEDIUM_FINDINGS=$(echo "$SCAN_RESULTS" | grep -c "medium")
                      LOW_FINDINGS=$(echo "$SCAN_RESULTS" | grep -c "low")

                      # Generate the report
                      cat << EOF > scan_report.txt
                      ===== SECURITY SCAN SUMMARY REPORT =====
                      Date: $(date)
                      Pipeline: <+pipeline.name>
                      Execution ID: <+pipeline.executionId>

                      FINDINGS STATISTICS:
                      - Total findings: $TOTAL_FINDINGS
                      - Critical severity: $CRITICAL_FINDINGS
                      - High severity: $HIGH_FINDINGS
                      - Medium severity: $MEDIUM_FINDINGS
                      - Low severity: $LOW_FINDINGS

                      TOP VULNERABILITIES:
                      $(echo "$SCAN_RESULTS" | grep -A 5 "critical\|high" | head -20)

                      For complete details, please review the full scan results.
                      EOF

                      echo "Report generated successfully at scan_report.txt"
                      cat scan_report.txt

                      # Export report content as an output variable
                      export REPORT_CONTENT=$(cat scan_report.txt)
                    envVariables:
                      SCAN_RESULTS: <+execution.steps.Semgrep_scan.output.outputVariables.SCAN_OUTPUT>
                    outputVariables:
                      - name: REPORT_CONTENT
                  timeout: 10m
              - step:
                  type: Run
                  name: set_pipeline_variables
                  identifier: set_pipeline_variables
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |
                      # Extract scan results and set pipeline variables
                      echo "Setting pipeline variables based on scan results..."

                      # Get scan results from previous steps
                      CRITICAL_ISSUES="<+execution.steps.Semgrep_scan.output.outputVariables.criticalIssues>"
                      HIGH_ISSUES="<+execution.steps.Semgrep_scan.output.outputVariables.highIssues>"
                      TOTAL_ISSUES="<+execution.steps.parse_results.output.outputVariables.totalIssues>"

                      # Set pipeline variables for downstream stages
                      export SCAN_STATUS="completed"
                      export HAS_CRITICAL_ISSUES="false"

                      if [ "$CRITICAL_ISSUES" -gt 0 ]; then
                        export HAS_CRITICAL_ISSUES="true"
                      fi

                      export SCAN_SUMMARY="Total: $TOTAL_ISSUES, Critical: $CRITICAL_ISSUES, High: $HIGH_ISSUES"
                    envVariables:
                      CRITICAL_ISSUES: <+execution.steps.Semgrep_scan.output.outputVariables.criticalIssues>
                      HIGH_ISSUES: <+execution.steps.Semgrep_scan.output.outputVariables.highIssues>
                      TOTAL_ISSUES: <+execution.steps.parse_results.output.outputVariables.totalIssues>
                    outputVariables:
                      - name: SCAN_STATUS
                      - name: HAS_CRITICAL_ISSUES
                      - name: SCAN_SUMMARY
                  timeout: 10m
              - step:
                  type: Run
                  name: conditional_failure
                  identifier: conditional_failure
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |
                      # Get severity counts from previous step
                      CRITICAL_COUNT=${CRITICAL_COUNT:-0}
                      HIGH_COUNT=${HIGH_COUNT:-0}
                      MEDIUM_COUNT=${MEDIUM_COUNT:-0}

                      echo "Scan results summary:"
                      echo "Critical issues: $CRITICAL_COUNT"
                      echo "High issues: $HIGH_COUNT"
                      echo "Medium issues: $MEDIUM_COUNT"

                      # Set failure thresholds
                      if [ "$CRITICAL_COUNT" -gt 0 ]; then
                        echo "FAIL: Critical security issues detected. Pipeline will fail."
                        exit 1
                      elif [ "$HIGH_COUNT" -gt 5 ]; then
                        echo "FAIL: Too many high severity issues detected ($HIGH_COUNT > 5). Pipeline will fail."
                        exit 1
                      elif [ "$MEDIUM_COUNT" -gt 10 ] && [ "$HIGH_COUNT" -gt 2 ]; then
                        echo "FAIL: Combined threshold of medium and high issues exceeded. Pipeline will fail."
                        exit 1
                      else
                        echo "PASS: Security scan passed threshold requirements. Pipeline will continue."
                        exit 0
                      fi
                    envVariables:
                      CRITICAL_COUNT: <+execution.steps.set_pipeline_variables.output.outputVariables.CRITICAL_COUNT>
                      HIGH_COUNT: <+execution.steps.set_pipeline_variables.output.outputVariables.HIGH_COUNT>
                      MEDIUM_COUNT: <+execution.steps.set_pipeline_variables.output.outputVariables.MEDIUM_COUNT>
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Abort
    - stage:
        name: Build_image
        identifier: Build_image
        description: Docker image build and push
        type: CI
        delegateSelectors:
          - docker-delegate
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: dockerhub
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerhub
                    repo: sankaranarayananmurali/maven-v1
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: Dockerfile
                    context: .
                    caching: true
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1
                      requests:
                        memory: 1Gi
                        cpu: 0.5
                  timeout: 10m
            rollbackSteps: []
    - stage:
        name: Build Approval
        identifier: Build_Approval
        description: Approval stage for Docker image
        type: Approval
        delegateSelectors:
          - docker-delegate
        spec:
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Docker Image Approval
                  identifier: Docker_image_Approval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
              - step:
                  type: Email
                  name: Email_Notification
                  identifier: Email_1
                  spec:
                    to: sankaranarayanan.m@xenovex.com
                    cc: ""
                    subject: Build Approved
                    body: |-
                      Hi,
                      Build is approved!
                  timeout: 10m
            rollbackSteps: []
        tags: {}
  description: This pipeline was updated by Harness AI on 2025-12-09 13:20:21 UTC by sankaranarayanan.m.
